version: '3.9'

services:
  integriadb:
    build:
      context: C:\Users\jjrr.13923\OneDrive - emtmadrid.es\Escritorio\projects-emt\container-db
      dockerfile: Dockerfile
    container_name: integriadb
    ports:
      - "3360:3306"
    networks:
      - integria-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  integria-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: integria-server
    ports:
      - "8022:8022"
    depends_on:
      integriadb:
        condition: service_healthy
    networks:
      - integria-network
    entrypoint: ["sh", "-c", "until nc -z integriadb 3306; do echo 'Waiting for DB...'; sleep 2; done; npm run serve:start"]

  integria-frontend:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: integria-frontend
    ports:
      - "8080:80"
    depends_on:
      - integria-server
    networks:
      - integria-network

networks:
  integria-network:
    driver: bridge

volumes:
  db_data: