name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['server', 'frontend']
        include:
          - service: 'server'
            context: './server'
            dockerfile: 'Dockerfile'
            image_name: 'integria-server'
          - service: 'frontend'
            context: '.'
            dockerfile: 'Dockerfile'
            image_name: 'integria-frontend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build and Push
        run: |
          docker build \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:v1 \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:latest \
            -f ${{ matrix.context }}/${{ matrix.dockerfile }} \
            ${{ matrix.context }}

          docker push ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:v1
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:latest

      - name: Verify pushed images
        run: |
          echo "Imágenes subidas:"
          echo " - ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:v1"
          echo " - ghcr.io/${{ secrets.GH_USERNAME }}/${{ matrix.image_name }}:latest"
