name: CI INTEGRIA-PROJECT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: integria_backup
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # Configuración inicial
      - name: 'Create email config dummy'
        working-directory: ./server
        run: |
          mkdir -p email-config
          echo "export const sendGmail = () => Promise.resolve();" > email-config/gmail-config.js

      # Base de datos
      - name: 'Wait for MySQL'
        run: |
          timeout 60 bash -c 'while ! nc -z 127.0.0.1 3306; do sleep 1; done'
          echo "✅ MySQL listo!"

      # - name: 'Run DB migrations'
      #   working-directory: ./server
      #   run: npm run migrate

      # - name: 'Verify seed file exists'
      #   run: ls -l server/db/seeders/test_data.sql

      # - name: 'Seed test data'
      #   working-directory: ./server
      #   run: npm run seed

      # Backend
      - name: 'Install backend dependencies'
        working-directory: ./server
        run: npm install

      - name: 'Run backend tests'
        working-directory: ./server
        run: npm run test

      # Frontend
      - name: 'Install frontend dependencies'
        working-directory: ./src
        run: npm install

      - name: 'Run frontend unit tests'
        working-directory: ./src
        run: npm run test:unit

      - name: 'Build frontend'
        working-directory: ./src
        run: npm run build

      # Cypress
      # - name: 'Run Cypress tests'
      #   working-directory: ./src
      #   run: npm run test:all
      #   env:
      #     DB_HOST: 127.0.0.1
      #     DB_USER: root
      #     DB_PASSWORD: root
      #     DB_NAME: integria_backup
      #     NODE_ENV: test
      #     CI: true

      - name: 'Completion message'
        if: always()
        run: echo "🚀 CI completo - Todos los tests ejecutados"
