name: CI INTEGRIA-PROJECT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: integria_backup
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Configuración dummy para email
      - name: 'Create email config dummy'
        working-directory: ./server
        run: |
          mkdir -p email-config
          echo "export default { user: 'test', pass: 'test' }" > email-config/gmail-config.js

      # Esperar MySQL
      - name: 'Wait for MySQL'
        run: |
          timeout 60 bash -c 'while ! nc -z 127.0.0.1 3306; do sleep 1; done'
          echo "✅ MySQL listo!"

      # Backend
      - name: 'Install backend dependencies'
        working-directory: ./server
        run: npm install

      - name: 'Start Express server'
        working-directory: ./server
        run: npm run dev &
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: integria_backup
          DB_PORT: 3306

      # Frontend
      - name: 'Install frontend dependencies'
        working-directory: ./src
        run: npm install

      - name: 'Build frontend'
        working-directory: ./src
        run: npm run build

      - name: 'Start Vite server'
        working-directory: ./src
        run: npm run dev &

      - name: 'Wait for servers'
        run: |
          npx wait-on http://localhost:5173 http://localhost:8022
          echo "✅ Servidores listos!"

      # Tests
      - name: 'Run Cypress tests'
        working-directory: ./src
        run: npm run test:all

      - name: 'Cleanup servers'
        run: |
          pkill -f "node.*dev" || true
