name: CI INTEGRIA-PROJECT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: integria_backup
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: 'Create email config dummy'
        working-directory: ./server
        run: |
          mkdir -p email-config
          echo "export const sendGmail = () => {}; export default { user: 'test', pass: 'test' }" > email-config/gmail-config.js

      - name: 'Wait for MySQL'
        run: |
          timeout 60 bash -c 'while ! nc -z 127.0.0.1 3306; do sleep 1; done'
          echo "✅ MySQL listo!"

      - name: 'Install backend dependencies'
        working-directory: ./server
        run: npm install

      - name: 'Install frontend dependencies'
        working-directory: ./src
        run: npm install

      - name: 'Run Cypress tests'
        working-directory: ./src
        run: npm run test:all
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: integria_backup
          DB_PORT: 3306
          NODE_ENV: test
          CI: true

      - name: 'Wait for Express server'
        run: |
          npx wait-on http://localhost:8022 || true
          echo "✅ Servidor Express listo"

      - name: 'Completion message'
        if: always()
        run: echo "🚀 Proceso de CI finalizado"
