name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: 'Display messages'
        run: echo "Hello, world!"
      - name: 'Finish job'
        run: echo "Job finished successfully"
