name: CI INTEGRIA-PROJECT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Backend (Express)
      - name: 'Install backend dependencies'
        working-directory: ./server
        run: npm install

      - name: 'Run backend tests'
        working-directory: ./server
        run: npm run test # Asegúrate de que esto ejecute vitest correctamente

      # Frontend (Vue 3)
      - name: 'Install frontend dependencies'
        working-directory: ./src
        run: npm install

      - name: 'Run Vitest unit tests'
        working-directory: ./src
        run: npm run test:unit

      - name: 'Run Cypress tests'
        working-directory: ./src
        run: npm run test:all

      - name: 'Build frontend'
        working-directory: ./src
        run: npm run build

      - name: 'Display success'
        run: echo "✅ CI completado!"
