name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run Vitest tests'
        run: npm run test:unit
      - name: 'Run Cypress tests'
        run: npm run test:all
      - name: 'Display messages'
        run: echo "Init jobs...!"
